### ISSUE TITLE
Exception in thread clearly-listener: task.worker.sw_ver is None

### ISSUE THREAD

**Issue by OmegaDroid** [rsalmei/clearly#42]
Hi,

I'm hitting an error in the clearly listener that stops new tasks from being processed. When using `cli.workers()` some workers have `sw:   `.

Here's the traceback:

```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/clearly/event_core/event_listener.py", line 103, in __run_listener
    self._celery_receiver.capture(limit=None, timeout=None, wakeup=True)
  File "/usr/local/lib/python3.7/site-packages/celery/events/receiver.py", line 93, in capture
    return list(self.consume(limit=limit, timeout=timeout, wakeup=wakeup))
  File "/usr/local/lib/python3.7/site-packages/kombu/mixins.py", line 197, in consume
    conn.drain_events(timeout=safety_interval)
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 321, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 979, in drain_events
    get(self._deliver, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/redis.py", line 370, in get
    ret = self.handle_event(fileno, event)
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/redis.py", line 352, in handle_event
    return self.on_readable(fileno), self
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/redis.py", line 348, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/redis.py", line 679, in _receive
    ret.append(self._receive_one(c))
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/redis.py", line 709, in _receive_one
    message, self._fanout_to_queue[exchange])
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 999, in _deliver
    callback(message)
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 633, in _callback
    return callback(message)
  File "/usr/local/lib/python3.7/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/usr/local/lib/python3.7/site-packages/kombu/messaging.py", line 590, in receive
    [callback(body, message) for callback in callbacks]
  File "/usr/local/lib/python3.7/site-packages/kombu/messaging.py", line 590, in <listcomp>
    [callback(body, message) for callback in callbacks]
  File "/usr/local/lib/python3.7/site-packages/celery/events/receiver.py", line 132, in _receive
    self.process(*self.event_from_message(body))
  File "/usr/local/lib/python3.7/site-packages/celery/events/receiver.py", line 71, in process
    handler and handler(event)
  File "/usr/local/lib/python3.7/site-packages/clearly/event_core/event_listener.py", line 110, in _process_event
    data = self._process_task_event(event)
  File "/usr/local/lib/python3.7/site-packages/clearly/event_core/event_listener.py", line 126, in _process_task_event
    task.result = EventListener.compile_task_result(task)
  File "/usr/local/lib/python3.7/site-packages/clearly/event_core/event_listener.py", line 144, in compile_task_result
    if task.worker.sw_ver < '4':
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

Do you know why our workers might be reporting an empty `sw_ver`?

I'm using:
clearly: 0.7.0
celery: 4.4.0rc3
python: 3.7

Thanks.

**Comment by rsalmei** [comment]
Hello @OmegaDroid ,
I imagine it would be the release candidate version of the celery.
Could you please test it with a stable version? 4.3.0 would do it.

**Comment by rsalmei** [comment]
Hello @OmegaDroid!
Please, could you sort it out?
I'm sorry, couldn't find the time yet to better address this.

**Comment by rsalmei** [comment]
Actually, this field is very important to support celery 3 and 4. It is based on it that I branch the processing of what is ahead. I don't actually know if it would be safe to just assume it is new if that field was missing.

**Comment by rsalmei** [comment]
Hey, I've just tested with celery 4.4.2, the latest one, and even the 4.4.0rc3 as you reported, and all works as expected:

```
In [3]: clearlycli.workers()
         celery@Rogerios-MacBook.local 74246
     sw: Darwin py-celery 4.4.0rc3
   load: [3.13, 2.57, 2.32] processed: 1001
fetched: 1 in 8.89ms (112.48/s)
```

I'm using the new clearly 0.8 line, with docker support and other things.
Going to close this one, please feel free to reopen if anything arises.
